version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/lib"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily