name: path_editor
description: "A Flutter widget for visually editing and manipulating SVG paths."
version: 0.0.1
homepage: https://github.com/NicolaVerbeeck/flutter_path_editor
issue_tracker: https://github.com/NicolaVerbeeck/flutter_path_editor/issues
topics: [ svg, path, editor ]


environment:
  sdk: ^3.4.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_parsing: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

funding:
  - https://buymeacoffee.com/nicolaverbn
  - https://ko-fi.com/nicolaverbeeck