name: Publish to github pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
      - run: flutter packages get
      - run: dart analyze --fatal-infos lib/
      - run: flutter packages get
        working-directory: ./example
      - run: dart analyze 
        working-directory: ./example
      - run: flutter create --platforms=web .
        working-directory: ./example
      - run: flutter build web --wasm --base-href /flutter_path_editor/
        working-directory: ./example
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./example/build/web"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4